#include "EmojiSegmenter.hpp"

#include <QVarLengthArray>

namespace Acheron {
namespace Core {

#define EMOJI_LINKAGE
#include <emoji_presentation_scanner.c>

// autogenerated
static CharacterCategory categorizeCodepoint(char32_t cp)
{
    if (cp == 0x20E3)
        return COMBINING_ENCLOSING_KEYCAP;
    if (cp == 0x20E0)
        return COMBINING_ENCLOSING_CIRCLE_BACKSLASH;
    if (cp == 0xFE0E)
        return VS15;
    if (cp == 0xFE0F)
        return VS16;
    if (cp == 0x200D)
        return ZWJ;
    if (cp == 0x1F3F4)
        return TAG_BASE;
    if (cp == 0xE007F)
        return TAG_TERM;
    if ((cp >= 0xE0030 && cp <= 0xE0039) || (cp >= 0xE0061 && cp <= 0xE007A))
        return TAG_SEQUENCE;
    if (cp >= 0x1F1E6 && cp <= 0x1F1FF)
        return REGIONAL_INDICATOR;
    if ((cp >= 0x0030 && cp <= 0x0039) || cp == 0x0023 || cp == 0x002A)
        return KEYCAP_BASE;

    // Emoji_Modifier (5 codepoints, 1 ranges)
    if ((cp >= 0x1F3FB && cp <= 0x1F3FF))
        return EMOJI_MODIFIER;

    // Emoji_Modifier_Base (134 codepoints, 40 ranges)
    // These default to emoji presentation, so return EMOJI_MODIFIER_BASE_EMOJI (4)
    if (cp == 0x261D || cp == 0x26F9 || (cp >= 0x270A && cp <= 0x270D) || cp == 0x1F385 ||
        (cp >= 0x1F3C2 && cp <= 0x1F3C4) || cp == 0x1F3C7 || (cp >= 0x1F3CA && cp <= 0x1F3CC) ||
        (cp >= 0x1F442 && cp <= 0x1F443) || (cp >= 0x1F446 && cp <= 0x1F450) ||
        (cp >= 0x1F466 && cp <= 0x1F478) || cp == 0x1F47C || (cp >= 0x1F481 && cp <= 0x1F483) ||
        (cp >= 0x1F485 && cp <= 0x1F487) || cp == 0x1F48F || cp == 0x1F491 || cp == 0x1F4AA ||
        (cp >= 0x1F574 && cp <= 0x1F575) || cp == 0x1F57A || cp == 0x1F590 ||
        (cp >= 0x1F595 && cp <= 0x1F596) || (cp >= 0x1F645 && cp <= 0x1F647) ||
        (cp >= 0x1F64B && cp <= 0x1F64F) || cp == 0x1F6A3 || (cp >= 0x1F6B4 && cp <= 0x1F6B6) ||
        cp == 0x1F6C0 || cp == 0x1F6CC || cp == 0x1F90C || cp == 0x1F90F ||
        (cp >= 0x1F918 && cp <= 0x1F91F) || cp == 0x1F926 || (cp >= 0x1F930 && cp <= 0x1F939) ||
        (cp >= 0x1F93C && cp <= 0x1F93E) || cp == 0x1F977 || (cp >= 0x1F9B5 && cp <= 0x1F9B6) ||
        (cp >= 0x1F9B8 && cp <= 0x1F9B9) || cp == 0x1F9BB || (cp >= 0x1F9CD && cp <= 0x1F9CF) ||
        (cp >= 0x1F9D1 && cp <= 0x1F9DD) || (cp >= 0x1FAC3 && cp <= 0x1FAC5) ||
        (cp >= 0x1FAF0 && cp <= 0x1FAF8))
        return EMOJI_MODIFIER_BASE_EMOJI;

    // Emoji_Presentation (1062 codepoints, 102 ranges)
    if ((cp >= 0x231A && cp <= 0x231B) || (cp >= 0x23E9 && cp <= 0x23EC) || cp == 0x23F0 ||
        cp == 0x23F3 || (cp >= 0x25FD && cp <= 0x25FE) || (cp >= 0x2614 && cp <= 0x2615) ||
        (cp >= 0x2648 && cp <= 0x2653) || cp == 0x267F || cp == 0x2693 || cp == 0x26A1 ||
        (cp >= 0x26AA && cp <= 0x26AB) || (cp >= 0x26BD && cp <= 0x26BE) ||
        (cp >= 0x26C4 && cp <= 0x26C5) || cp == 0x26CE || cp == 0x26D4 || cp == 0x26EA ||
        (cp >= 0x26F2 && cp <= 0x26F3) || cp == 0x26F5 || cp == 0x26FA || cp == 0x26FD ||
        cp == 0x2705 || cp == 0x2728 || cp == 0x274C || cp == 0x274E ||
        (cp >= 0x2753 && cp <= 0x2755) || cp == 0x2757 || (cp >= 0x2795 && cp <= 0x2797) ||
        cp == 0x27B0 || cp == 0x27BF || (cp >= 0x2B1B && cp <= 0x2B1C) || cp == 0x2B50 ||
        cp == 0x2B55 || cp == 0x1F004 || cp == 0x1F0CF || cp == 0x1F18E ||
        (cp >= 0x1F191 && cp <= 0x1F19A) || cp == 0x1F201 || cp == 0x1F21A || cp == 0x1F22F ||
        (cp >= 0x1F232 && cp <= 0x1F236) || (cp >= 0x1F238 && cp <= 0x1F23A) ||
        (cp >= 0x1F250 && cp <= 0x1F251) || (cp >= 0x1F300 && cp <= 0x1F320) ||
        (cp >= 0x1F32D && cp <= 0x1F335) || (cp >= 0x1F337 && cp <= 0x1F37C) ||
        (cp >= 0x1F37E && cp <= 0x1F384) || (cp >= 0x1F386 && cp <= 0x1F393) ||
        (cp >= 0x1F3A0 && cp <= 0x1F3C1) || (cp >= 0x1F3C5 && cp <= 0x1F3C6) ||
        (cp >= 0x1F3C8 && cp <= 0x1F3C9) || (cp >= 0x1F3CF && cp <= 0x1F3D3) ||
        (cp >= 0x1F3E0 && cp <= 0x1F3F0) || (cp >= 0x1F3F8 && cp <= 0x1F3FA) ||
        (cp >= 0x1F400 && cp <= 0x1F43E) || cp == 0x1F440 || (cp >= 0x1F444 && cp <= 0x1F445) ||
        (cp >= 0x1F451 && cp <= 0x1F465) || (cp >= 0x1F479 && cp <= 0x1F47B) ||
        (cp >= 0x1F47D && cp <= 0x1F480) || cp == 0x1F484 || (cp >= 0x1F488 && cp <= 0x1F48E) ||
        cp == 0x1F490 || (cp >= 0x1F492 && cp <= 0x1F4A9) || (cp >= 0x1F4AB && cp <= 0x1F4FC) ||
        (cp >= 0x1F4FF && cp <= 0x1F53D) || (cp >= 0x1F54B && cp <= 0x1F54E) ||
        (cp >= 0x1F550 && cp <= 0x1F567) || cp == 0x1F5A4 || (cp >= 0x1F5FB && cp <= 0x1F644) ||
        (cp >= 0x1F648 && cp <= 0x1F64A) || (cp >= 0x1F680 && cp <= 0x1F6A2) ||
        (cp >= 0x1F6A4 && cp <= 0x1F6B3) || (cp >= 0x1F6B7 && cp <= 0x1F6BF) ||
        (cp >= 0x1F6C1 && cp <= 0x1F6C5) || (cp >= 0x1F6D0 && cp <= 0x1F6D2) ||
        (cp >= 0x1F6D5 && cp <= 0x1F6D8) || (cp >= 0x1F6DC && cp <= 0x1F6DF) ||
        (cp >= 0x1F6EB && cp <= 0x1F6EC) || (cp >= 0x1F6F4 && cp <= 0x1F6FC) ||
        (cp >= 0x1F7E0 && cp <= 0x1F7EB) || cp == 0x1F7F0 || (cp >= 0x1F90D && cp <= 0x1F90E) ||
        (cp >= 0x1F910 && cp <= 0x1F917) || (cp >= 0x1F920 && cp <= 0x1F925) ||
        (cp >= 0x1F927 && cp <= 0x1F92F) || cp == 0x1F93A || (cp >= 0x1F93F && cp <= 0x1F945) ||
        (cp >= 0x1F947 && cp <= 0x1F976) || (cp >= 0x1F978 && cp <= 0x1F9B4) || cp == 0x1F9B7 ||
        cp == 0x1F9BA || (cp >= 0x1F9BC && cp <= 0x1F9CC) || cp == 0x1F9D0 ||
        (cp >= 0x1F9DE && cp <= 0x1F9FF) || (cp >= 0x1FA70 && cp <= 0x1FA7C) ||
        (cp >= 0x1FA80 && cp <= 0x1FA8A) || (cp >= 0x1FA8E && cp <= 0x1FAC2) || cp == 0x1FAC6 ||
        cp == 0x1FAC8 || (cp >= 0x1FACD && cp <= 0x1FADC) || (cp >= 0x1FADF && cp <= 0x1FAEA) ||
        cp == 0x1FAEF)
        return EMOJI_EMOJI_PRESENTATION;

    // Emoji, text presentation (198 codepoints, 114 ranges)
    if (cp == 0x00A9 || cp == 0x00AE || cp == 0x203C || cp == 0x2049 || cp == 0x2122 ||
        cp == 0x2139 || (cp >= 0x2194 && cp <= 0x2199) || (cp >= 0x21A9 && cp <= 0x21AA) ||
        cp == 0x2328 || cp == 0x23CF || (cp >= 0x23ED && cp <= 0x23EF) ||
        (cp >= 0x23F1 && cp <= 0x23F2) || (cp >= 0x23F8 && cp <= 0x23FA) || cp == 0x24C2 ||
        (cp >= 0x25AA && cp <= 0x25AB) || cp == 0x25B6 || cp == 0x25C0 ||
        (cp >= 0x25FB && cp <= 0x25FC) || (cp >= 0x2600 && cp <= 0x2604) || cp == 0x260E ||
        cp == 0x2611 || cp == 0x2618 || cp == 0x2620 || (cp >= 0x2622 && cp <= 0x2623) ||
        cp == 0x2626 || cp == 0x262A || (cp >= 0x262E && cp <= 0x262F) ||
        (cp >= 0x2638 && cp <= 0x263A) || cp == 0x2640 || cp == 0x2642 ||
        (cp >= 0x265F && cp <= 0x2660) || cp == 0x2663 || (cp >= 0x2665 && cp <= 0x2666) ||
        cp == 0x2668 || cp == 0x267B || cp == 0x267E || cp == 0x2692 ||
        (cp >= 0x2694 && cp <= 0x2697) || cp == 0x2699 || (cp >= 0x269B && cp <= 0x269C) ||
        cp == 0x26A0 || cp == 0x26A7 || (cp >= 0x26B0 && cp <= 0x26B1) || cp == 0x26C8 ||
        cp == 0x26CF || cp == 0x26D1 || cp == 0x26D3 || cp == 0x26E9 ||
        (cp >= 0x26F0 && cp <= 0x26F1) || cp == 0x26F4 || (cp >= 0x26F7 && cp <= 0x26F8) ||
        cp == 0x2702 || (cp >= 0x2708 && cp <= 0x2709) || cp == 0x270F || cp == 0x2712 ||
        cp == 0x2714 || cp == 0x2716 || cp == 0x271D || cp == 0x2721 ||
        (cp >= 0x2733 && cp <= 0x2734) || cp == 0x2744 || cp == 0x2747 ||
        (cp >= 0x2763 && cp <= 0x2764) || cp == 0x27A1 || (cp >= 0x2934 && cp <= 0x2935) ||
        (cp >= 0x2B05 && cp <= 0x2B07) || cp == 0x3030 || cp == 0x303D || cp == 0x3297 ||
        cp == 0x3299 || (cp >= 0x1F170 && cp <= 0x1F171) || (cp >= 0x1F17E && cp <= 0x1F17F) ||
        cp == 0x1F202 || cp == 0x1F237 || cp == 0x1F321 || (cp >= 0x1F324 && cp <= 0x1F32C) ||
        cp == 0x1F336 || cp == 0x1F37D || (cp >= 0x1F396 && cp <= 0x1F397) ||
        (cp >= 0x1F399 && cp <= 0x1F39B) || (cp >= 0x1F39E && cp <= 0x1F39F) ||
        (cp >= 0x1F3CD && cp <= 0x1F3CE) || (cp >= 0x1F3D4 && cp <= 0x1F3DF) || cp == 0x1F3F3 ||
        cp == 0x1F3F5 || cp == 0x1F3F7 || cp == 0x1F43F || cp == 0x1F441 || cp == 0x1F4FD ||
        (cp >= 0x1F549 && cp <= 0x1F54A) || (cp >= 0x1F56F && cp <= 0x1F570) || cp == 0x1F573 ||
        (cp >= 0x1F576 && cp <= 0x1F579) || cp == 0x1F587 || (cp >= 0x1F58A && cp <= 0x1F58D) ||
        cp == 0x1F5A5 || cp == 0x1F5A8 || (cp >= 0x1F5B1 && cp <= 0x1F5B2) || cp == 0x1F5BC ||
        (cp >= 0x1F5C2 && cp <= 0x1F5C4) || (cp >= 0x1F5D1 && cp <= 0x1F5D3) ||
        (cp >= 0x1F5DC && cp <= 0x1F5DE) || cp == 0x1F5E1 || cp == 0x1F5E3 || cp == 0x1F5E8 ||
        cp == 0x1F5EF || cp == 0x1F5F3 || cp == 0x1F5FA || cp == 0x1F6CB ||
        (cp >= 0x1F6CD && cp <= 0x1F6CF) || (cp >= 0x1F6E0 && cp <= 0x1F6E5) || cp == 0x1F6E9 ||
        cp == 0x1F6F0 || cp == 0x1F6F3)
        return EMOJI_TEXT_PRESENTATION;

    // Extended_Pictographic, not otherwise categorized (1453 codepoints, 36 ranges)
    if ((cp >= 0x1F02C && cp <= 0x1F02F) || (cp >= 0x1F094 && cp <= 0x1F09F) ||
        (cp >= 0x1F0AF && cp <= 0x1F0B0) || cp == 0x1F0C0 || cp == 0x1F0D0 ||
        (cp >= 0x1F0F6 && cp <= 0x1F0FF) || (cp >= 0x1F1AE && cp <= 0x1F1E5) ||
        (cp >= 0x1F203 && cp <= 0x1F20F) || (cp >= 0x1F23C && cp <= 0x1F23F) ||
        (cp >= 0x1F249 && cp <= 0x1F24F) || (cp >= 0x1F252 && cp <= 0x1F25F) ||
        (cp >= 0x1F266 && cp <= 0x1F2FF) || (cp >= 0x1F6D9 && cp <= 0x1F6DB) ||
        (cp >= 0x1F6ED && cp <= 0x1F6EF) || (cp >= 0x1F6FD && cp <= 0x1F6FF) ||
        (cp >= 0x1F7DA && cp <= 0x1F7DF) || (cp >= 0x1F7EC && cp <= 0x1F7EF) ||
        (cp >= 0x1F7F1 && cp <= 0x1F7FF) || (cp >= 0x1F80C && cp <= 0x1F80F) ||
        (cp >= 0x1F848 && cp <= 0x1F84F) || (cp >= 0x1F85A && cp <= 0x1F85F) ||
        (cp >= 0x1F888 && cp <= 0x1F88F) || (cp >= 0x1F8AE && cp <= 0x1F8AF) ||
        (cp >= 0x1F8BC && cp <= 0x1F8BF) || (cp >= 0x1F8C2 && cp <= 0x1F8CF) ||
        (cp >= 0x1F8D9 && cp <= 0x1F8FF) || (cp >= 0x1FA58 && cp <= 0x1FA5F) ||
        (cp >= 0x1FA6E && cp <= 0x1FA6F) || (cp >= 0x1FA7D && cp <= 0x1FA7F) ||
        (cp >= 0x1FA8B && cp <= 0x1FA8D) || cp == 0x1FAC7 || (cp >= 0x1FAC9 && cp <= 0x1FACC) ||
        (cp >= 0x1FADD && cp <= 0x1FADE) || (cp >= 0x1FAEB && cp <= 0x1FAEE) ||
        (cp >= 0x1FAF9 && cp <= 0x1FAFF) || (cp >= 0x1FC00 && cp <= 0x1FFFD))
        return EMOJI;

    return OTHER;
}

// Count the number of emoji presentation sequences in a text string using the
// emoji-segmenter state machine. Returns -1 if any non-emoji, non-whitespace
// content is found. Returns the emoji sequence count otherwise (0 if all whitespace).
int countUnicodeEmojisSegmented(const QString &text)
{
    if (text.isEmpty())
        return 0;

    // Build categorized array: one entry per codepoint (not per UTF-16 unit).
    // Also track which codepoints are whitespace so we can skip them.
    QVarLengthArray<CharacterCategory, 64> categories;
    QVarLengthArray<bool, 64> isWhitespace;

    for (int i = 0; i < text.size(); ++i) {
        const QChar ch = text[i];
        char32_t cp;
        if (ch.isHighSurrogate() && i + 1 < text.size() && text[i + 1].isLowSurrogate()) {
            cp = QChar::surrogateToUcs4(ch, text[++i]);
        } else {
            cp = ch.unicode();
        }

        if (QChar::isSpace(cp)) {
            // Whitespace is OTHER to the scanner — it will produce a non-emoji segment.
            // We track it separately so we can allow it.
            categories.append(OTHER);
            isWhitespace.append(true);
        } else {
            categories.append(categorizeCodepoint(cp));
            isWhitespace.append(false);
        }
    }

    const emoji_text_iter_t begin = categories.data();
    const emoji_text_iter_t end = begin + categories.size();
    emoji_text_iter_t pos = const_cast<emoji_text_iter_t>(begin);

    int emojiCount = 0;

    while (pos < end) {
        bool isEmoji = false;
        bool hasVs = false;
        emoji_text_iter_t segEnd = scan_emoji_presentation(pos, end, &isEmoji, &hasVs);

        if (segEnd == pos) {
            // Should not happen, but guard against infinite loop.
            ++pos;
            continue;
        }

        int segStart = static_cast<int>(pos - begin);
        int segLen = static_cast<int>(segEnd - pos);

        if (isEmoji) {
            emojiCount++;
        } else {
            // Non-emoji segment: verify it's all whitespace.
            for (int j = segStart; j < segStart + segLen; ++j) {
                if (!isWhitespace[j])
                    return -1;
            }
        }

        pos = segEnd;
    }

    return emojiCount;
}

} // namespace Core
} // namespace Acheron
